// Trying variant with all HTML generated by JS 

// let test = document.createElement("p");
// let text = document.createTextNode("Hello");
// test.appendChild(text);
// test.style.background = 'yellow';
// document.body.appendChild(test);

let SIZE = 6;
let color = {h: 108,
			 s: "100%",
			 l: "40%"
			};
let bulbes = [];


function initStage () {
	document.getElementsByClassName("bottomPart")[0].innerHTML = "";
	bulbes = [];
	clearField();
	createBulbs();
}
function changeFieldSize(value){
	SIZE = value;
	initStage();
}


function createBulbs(){
	let parent = document.getElementsByClassName("bottomPart")[0];
	parent.addEventListener("mousemove", moveFunction);
	parent.addEventListener("mousedown", createNewColor);
	parent.addEventListener("click", clickFunction);
	parent.addEventListener("dblclick", removeColor);


	for(let i=0; i<SIZE; i++){
		let row = document.createElement("div");

		for(let j=0; j<SIZE; j++){
			let bulb = document.createElement("div");
			bulb.style.display = 'block';
			bulb.style.width = '40px';
			bulb.style.height = '40px';
			bulb.style.borderRadius = '50%';
			bulb.style.margin  = '4px';
			bulb.pointerEvents = 'none';
			bulb.style.position = 'relative';
			bulb.style.border = "1px solid black";
			bulb.style.boxShadow = '0 0 10px white';

			bulb.id = `bulb-${j+(i*SIZE)}`;
			bulbes.push(bulb);

			row.appendChild(bulb);
		}
		row.style.position = 'relative';
		row.style.margin = 'auto';
		row.style.display = 'flex';
		row.style.maxWidth = '800px';
		row.style.justifyContent = 'center';
		row.style.alignItems = 'center';
		parent.appendChild(row);
	}

}


function clickFunction(target){
	let bulb = document.getElementById(target.toElement.id);
	if(bulb!=null){
		bulb.style.background = `radial-gradient(white, hsl(${color.h},${color.s},${color.l}))`;
	}
}
function moveFunction(target){
	if(target.buttons == 1){
	let bulb = document.getElementById(target.toElement.id);
		if(bulb!=null){
			bulb.style.background = `radial-gradient(white, hsl(${color.h},${color.s},${color.l}))`;
		}
	}
}
function createNewColor(){
	color.h = Math.round(Math.random()*360-1);
	if(Math.random()*5 > 4){
		color.l = Math.round(Math.random()*20-1)+"%";
	}else{
		color.l = "30%";
	}
}

function removeColor(target){
	let bulb = document.getElementById(target.toElement.id);
	if(bulb!=null){
		bulb.style.background = 'grey';
	}
}
function clearField(){
	bulbes.forEach(el => el.style.background = 'grey');
}